//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zork.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Away, peasant!
        ///	&gt;Stay! How came you by that horse?
        ///		&lt;Is it any matter of yours? (rides away).
        /// </summary>
        internal static string alfred {
            get {
                return ResourceManager.GetString("alfred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;A penny for one less fortunate, sir?
        ///	&gt;Away, thou elvish-mark’d, abortive, rooting hog!
        ///	&gt;Here, have a hundred pennies, that much I can spare.
        ///		&lt;Thank you!
        ///	&gt;[money]Lend me your thoughts, madam, and I will give you half a pound.
        ///		&lt;Gracious generous sir, I must confess then, what your son did tell me.
        ///			&gt;His secrets are his own, I&apos;m sure.
        ///			&gt;Pray tell.
        ///				&lt;Ignatius and his friends, Kelsey, Bevis and Barden, found drunk Reginald on the road and took from him a good deal of money.[brigands_stole_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string audrey {
            get {
                return ResourceManager.GetString("audrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Hello mister.
        ///	&gt;Seen anything suspicious?
        ///		&lt;Yes sir! I was following Cecil when she went into the Barclay&apos;s manor, but I think she left in a bag.[suspicious_bag_seen]
        ///			&gt;Grievous indeed. Speak naught of this until I have investigated the matter..
        /// </summary>
        internal static string barden {
            get {
                return ResourceManager.GetString("barden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Hello mister.
        ///	&gt;Seen anything suspicious?
        ///		&lt;Not with my eyes, sir, but Barden told the strangest tale! He saw Cecil enter into the Barclay manor, and never leave, but a bag large enough to contain her did.[suspicious_bag_seen]
        ///			&gt;Grievous indeed. Speak naught of this until I have investigated the matter..
        /// </summary>
        internal static string bevis {
            get {
                return ResourceManager.GetString("bevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Good day, sir!
        ///	&gt;[skillet_missing]I was speaking with the cook, Maxwell. He said you might know something about this skillet.
        ///		&lt;I know naught, I assure thee.
        ///			&gt;[suspicious_bag_seen]The sweat upon your brow does betray thee, Burton. You were seen leaving this place with a package rather too large to be kitchen scraps!
        ///				&lt;What of it? Make these claims solid or leave them be.
        ///					&gt;I will prove naught but that my blade is sharp, brigand!
        ///	&gt;How goes thee?
        ///		&lt;Fine, fine..
        /// </summary>
        internal static string burton {
            get {
                return ResourceManager.GetString("burton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Sherlock! What&apos;s new?
        ///	&gt;How are you?
        ///		&lt;It&apos;s a fine day for a stroll, don&apos;t you think?
        ///			&gt;Not really; my wife has been missing for several days.
        ///			&gt;Whatever. Let me know if you see my wife.
        ///	&gt;Can you help me?
        ///		&lt;What do you need?
        ///			&gt;Find the murderer!
        ///				&lt;First find out who did it.
        ///			&gt;I&apos;m looking for a weapon.
        ///				&lt;If you&apos;re going to take the law into your own hands, I can&apos;t help you.
        ///			&gt;I&apos;m wounded. Can you help me?
        ///				&lt;Actually, I never really liked you. Good luck bleeding!.
        /// </summary>
        internal static string constable_barney {
            get {
                return ResourceManager.GetString("constable_barney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Can I offer you some sack at my inn, sir?
        ///	&gt;Perhaps some other time. I&apos;m investigating a murder here. Seen anything suspicious?
        ///		&lt;Nay, save that Audrey had rather a lot of coin to spend last night.[audrey_rich]
        ///	&gt;Indeed, lead the way!
        ///		&lt;Oh... I.. nobody ever agrees. Honestly, I don&apos;t even know if there is an inn in this game.
        ///	&gt;[ask_emerson]I spoke with your ostler, Geoffrey. Whatever is troubling him so?
        ///		&lt;Good riddance to him! I sent him away; a useless cream faced loon is he. I had a distinguis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emerson {
            get {
                return ResourceManager.GetString("emerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Hello, sir. I hope you are more fortunate this day than I.
        ///	&gt;Why the long face, ostler?
        ///		&lt;On my watch, two nights ago a royal horse was stolen, clad in royal purple, accompanied by no royal curple.
        ///			&gt;Good luck with that!
        ///	&gt;I don&apos;t really care. I&apos;m looking for information about Cecil. She was found dead thismorning.
        ///		&lt;Perhaps you should ask the inn keeper, Emerson. He usually knows where the whores are to be found.[ask_emerson]
        ///			&gt;Thank you for the advice.
        ///			&gt;Not so fast, brigand. You murdered  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string geoffrey {
            get {
                return ResourceManager.GetString("geoffrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;What?
        ///	&gt;Who are you?
        ///		&lt;[introduced]I&apos;ve told thee once, and shall not repeat it! Begone peasant!
        ///		&lt;Sir Henry, heir to the throne of England. Begone peasant![introduced]
        ///	&gt;You bastard! Murderer!
        ///		&lt;Thou lowly cozener, thou purple-hued malt worm, thou drone, thou snail, thou slug, thou sot! I defy thee to prove by the blade what thy wretched lips do conjure!
        ///	&gt;I&apos;d like to ask you a few questions.
        ///		&lt;Ask away.
        ///			&gt;How came you by that red cloak?
        ///				&lt;It was bequeathed by my late aunt&apos;s nephew&apos;s dog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string henry {
            get {
                return ResourceManager.GetString("henry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Papa!
        ///	&gt;Son, how goes thee?
        ///		&lt;As excellent as excellent lads will be, father. Fare well!
        ///	&gt;[brigands_stole_from_reginald]Confess your sins, son. I know them already.
        ///		&lt;I swear, the toad was already dead!
        ///			&gt;The *other* sins, son.
        ///				&lt;Oh, well. I suppose since you know already, I can just excuse myself.
        ///					&gt;Not so fast. Hand over the money you stole from Reginald.
        ///						&lt;... I&apos;ve already spent it, I&apos;m afraid. (hands over empty purse)[purse]
        ///							&gt;What? How could you possibly have, so quickl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ignatius {
            get {
                return ResourceManager.GetString("ignatius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Hello sir!
        ///	&gt;[brigands_stole_from_reginald]You sinner! Repent thy crimes to thy father immediately, or I shall tell him for you!
        ///		&lt;Darn.
        ///	&gt;A fair day for a stroll, is it not?
        ///		&lt;Indeed, a better one I could not wish. Good day to you!
        ///			&gt;Not so fast, brigand. You murdered Cecil, did you not?
        ///				&lt;Prove it or die!.
        /// </summary>
        internal static string kelsey {
            get {
                return ResourceManager.GetString("kelsey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;[insulted_lady_barclay]&lt;I have no words to exchange with thee.
        ///&lt;I pray you, what is&apos;t o&apos;clock, good sir?
        ///	&gt;I think it two o&apos;clock, madam.
        ///		&lt;I thank thee, and my leave I take.
        ///	&gt;I think it five o&apos;clock, madam.
        ///		&lt;I thank thee, in good grace.
        ///	&gt;I think it eight o&apos;clock, madam.
        ///		&lt;Why, the sun doest speak otherwise, thou three-inch fool! Your wit’s as thick as a Tewkesbury mustard.[wrongtime]
        ///	&gt;You should ask me what time o&apos;day, for there isn&apos;t a clock in London rings truer than the sun on such a fin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lady_barclay {
            get {
                return ResourceManager.GetString("lady_barclay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Good day, sir!
        ///	&gt;[suspicious_bag_seen]A boy told me something unusual; that Cecil came into this manor last evening but left it not. Is she still here?
        ///		&lt;I know nothing of that sir. But if you do speak with our servant Burton, do tell him to return the skillet; it is hard cooking without it. Curse his clay-brained guts, that knotty-pated fool![skillet_missing]
        ///	&gt;[iron_skillet]Is this household missing an iron skillet? I came across one bearing the mark of the Barclays.
        ///		&lt;Indeed! Thank thee greatly, I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maxwell {
            get {
                return ResourceManager.GetString("maxwell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family trees
        ///
        ///Lady_Margaret_Beaufort
        ///	Henry_VII
        ///	Elizabeth_of_York
        ///		Arthur_Prince_of_Wales
        ///		Henry_VIII
        ///
        ///Catherine_of_Aragon
        ///Arthur_Prince_of_Wales
        ///
        ///Sir_Barclay
        ///Lady_Barclay
        ///	Ansley_Duke_of_York
        ///	Kelsey
        ///	
        ///Maxwell, Sir_Barclay&apos;s cook
        ///
        ///Burton, servant of Sir_Barclay
        ///
        ///Reginald
        ///Alfred (brother of Reginald)
        ///
        ///Brigands:
        ///Kelsey (15 years old)
        ///Barden (14 years old)
        ///Bevis (14 years old)
        ///Ignatius (your son, 15)
        ///
        ///Emerson, innkeeper
        ///
        ///Geoffrey, ostler
        ///
        ///Cecil (a whore)
        ///
        ///Audrey (a beggar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string outline {
            get {
                return ResourceManager.GetString("outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I know thy face, sir!
        ///	&gt;Well, this is awkward. (leave)
        ///	&gt;Indeed; how goes thee?
        ///		&lt;If my wife were a hobby horse I would count myself luckier; this very morning I was waylaid, my purse ta&apos;en and left to wait for better fortune!
        ///			&gt;[purse]Indeed, did it look like this here purse?
        ///				&lt;Why yes! (takes purse) It&apos;s rather lighter than when it left me! How came you by it?
        ///					&gt;[villains_described]I came across the villains, precisely as you described; and one by one slew them in answering for their crim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reginald {
            get {
                return ResourceManager.GetString("reginald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Hello sir.
        ///	&gt;Good day. I&apos;m looking for clues as to the murder of one Cecil, a lady of unsavoury profession.
        ///		&lt;I know nothing.
        ///	&gt;[brigands_stole_from_reginald]I need to talk to you about your son. It will be hard to hear.
        ///		&lt;To be a father is sometimes to hear what must be heard. Speak freely.
        ///			&gt;Kelsey, along with my own son, did steal from a drunkard by the name of Reginald, some half pound at least, I should think.
        ///				&lt;For shame, for shame! That my blood should thus be shown as thick as mud.
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sir_barclay {
            get {
                return ResourceManager.GetString("sir_barclay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbey Road
        ///Abbey Street
        ///Abbot&apos;s Road
        ///Abbotswell Street
        ///Abingdon Street
        ///Acacia Road
        ///Acorn Street
        ///Acton Street
        ///Adam Street
        ///Adams Mews
        ///Adelaide Place
        ///Adelaide Road
        ///Admiral Street
        ///Agnes Street
        ///Albany Street
        ///Albemarle Street
        ///Albert Cottages
        ///Albert Mews
        ///Albert Road
        ///Albert Square
        ///Albert Street
        ///Albion Mews
        ///Albion Place
        ///Albion Road
        ///Albion Street
        ///Aldred Road
        ///Alexander Street
        ///Alexandra Road
        ///Alexandra Villas
        ///Alfred Cottages
        ///Alfred Mews
        ///Alfred Place
        ///Alfred Street
        ///Alfred&apos;s Place
        ///Allen St [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string streetnames {
            get {
                return ResourceManager.GetString("streetnames", resourceCulture);
            }
        }
    }
}
